DELETE http://localhost:3001/api/blogs/64d24b8b2a6dd86f33d3d0cc
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI2NGQyNGIzYjJhNmRkODZmMzNkM2QwYzUiLCJpYXQiOjE2OTE1NjY0OTgsImV4cCI6MTY5MTU3MDA5OH0.4ADabdfYyy4EIcs2nvE4n1j3SKieSGgf7VR9zs1JmUY